{
  "openapi":"3.0.2",
  "info": {
    "title":"DevRadar",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/devradar-api/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "tags": ["Sessions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "code": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "code": "41245847401cd95e1c3c"
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/User"
          },
          "404": {
            "description": "Developer does not exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Developer does not exists",
                  "code": 144,
                  "docs": "https://github.com/DiegoVictor/devradar-api#errors-reference"
                }
              }
            }
          },
          "503": {
            "$ref": "#/components/responses/ServiceUnavailable"
          }
        }
      }
    },
    "/search": {
      "get": {
        "tags": ["Search"],
        "parameters": [
          {
            "in": "query",
            "name": "latitude",
            "required": true,
            "schema": {
              "type": "number"
            },
            "example": 36.6812
          },
          {
            "in": "query",
            "name": "longitude",
            "required": true,
            "schema": {
              "type": "number"
            },
            "example": 81.6031
          },
          {
            "in": "query",
            "name": "techs",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "ReactJS, Node.js"
          }
        ],
        "responses": {
          "200": {
            "description": "Search nearest developers with the same techs",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/Developer"
                      },
                      {
                        "title": "Developer",
                        "properties": {
                          "url": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "_id": "613514c6606e092854b195a6",
                    "techs": [
                      "Node.js",
                      "ReactJS",
                      "React Native"
                    ],
                    "name": "Diego Victor",
                    "avatar_url": "https://avatars.githubusercontent.com/u/15165349?v=4",
                    "bio": "I have been working with PHP/Laravel and JavaScript/Node.js for +5 years. Recently I started studying ReactJs and React Native :)\r\n",
                    "github_username": "DiegoVictor",
                    "location": {
                      "coordinates": [
                        81.6031,
                        36.6812
                      ]
                    },
                    "url": "http://localhost:3333/v1/developers/613514c6606e092854b195a6"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/developers": {
      "get": {
        "tags": ["Developers"],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List developers",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/Developer"
                      },
                      {
                        "title": "Developer",
                        "properties": {
                          "url": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "_id": "613514c6606e092854b195a6",
                    "techs": [
                      "Node.js",
                      "ReactJS",
                      "React Native"
                    ],
                    "name": "Diego Victor",
                    "avatar_url": "https://avatars.githubusercontent.com/u/15165349?v=4",
                    "bio": "I have been working with PHP/Laravel and JavaScript/Node.js for +5 years. Recently I started studying ReactJs and React Native :)\r\n",
                    "github_username": "DiegoVictor",
                    "location": {
                      "coordinates": [
                        81.6031,
                        36.6812
                      ]
                    },
                    "url": "http://localhost:3333/v1/developers/613514c6606e092854b195a6"
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              },
              "Link": {
                "description": "Next, Previous, First and Last page's urls",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Developers"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "code",
                  "techs",
                  "latitude",
                  "longitude"
                ],
                "properties": {
                  "code": {
                    "type": "string"
                  },
                  "techs": {
                    "type": "string"
                  },
                  "latitude": {
                    "type": "number"
                  },
                  "longitude": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "code": "fd674539592cba6cd49c",
                "techs": "Node.js, ReactJS, React Native",
                "latitude": 36.6812,
                "longitude": 81.6031
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Create new developers",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "developer": {
                      "$ref": "#/components/schemas/Developer"
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "developer": {
                    "name": "Diego Victor",
                    "avatar_url": "https://avatars.githubusercontent.com/u/15165349?v=4",
                    "bio": "I have been working with PHP/Laravel and JavaScript/Node.js for +5 years. Recently I started studying ReactJs and React Native :)\r\n",
                    "github_username": "DiegoVictor",
                    "techs": [
                      "Node.js",
                      "ReactJS",
                      "React Native"
                    ],
                    "location": {
                      "coordinates": [
                        81.6031,
                        36.6812
                      ]
                    },
                    "_id": "613514c6606e092854b195a6"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzUxNGM2NjA2ZTA5Mjg1NGIxOTVhNiIsImlhdCI6MTYzMDg2ODY3OCwiZXhwIjoxNjMxNDczNDc4fQ.ajUEtNnbmJql1hLWl5PT7sk-6c9_JGPy4HVDBEhVWXw"
                }
              }
            }
          },
          "400": {
            "description": "You are already registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "You are already registered",
                  "code": 140,
                  "docs": "https://github.com/DiegoVictor/devradar-api#errors-reference"
                }
              }
            }
          },
          "503": {
            "$ref": "#/components/responses/ServiceUnavailable"
          }
        }
      },
    },
  },
  "components": {
    "schemas": {
      "Developer": {
        "properties": {
          "_id": {
            "type": "string"
          },
          "techs": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "name": {
            "type": "string"
          },
          "avatar_url": {
            "type": "string"
          },
          "bio": {
            "type": "string"
          },
          "github_username": {
            "type": "string"
          },
          "location": {
            "type": "object",
            "properties": {
              "coordinates": {
                "type": "array",
                "items": {
                  "type": "number"
                }
              }
            }
          }
        }
      },
      "Error": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    },
    "responses": {
      "User": {
        "description": "Return a Bearer Token and developer's information",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "developer": {
                  "$ref": "#/components/schemas/Developer"
                },
                "token": {
                  "type": "string"
                }
              }
            },
            "example": {
              "developer": {
                "_id": "613514c6606e092854b195a6",
                "techs": [
                  "Node.js",
                  "ReactJS",
                  "React Native"
                ],
                "name": "Diego Victor",
                "avatar_url": "https://avatars.githubusercontent.com/u/15165349?v=4",
                "bio": "I have been working with PHP/Laravel and JavaScript/Node.js for +5 years. Recently I started studying ReactJs and React Native :)\r\n",
                "github_username": "DiegoVictor",
                "location": {
                  "coordinates": [
                    81.6031,
                    36.6812
                  ]
                }
              },
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzUxNGM2NjA2ZTA5Mjg1NGIxOTVhNiIsImlhdCI6MTYzMDg2OTA0NiwiZXhwIjoxNjMxNDczODQ2fQ.WPAFQvVr4aGleFCggs4EV6T9EjOEZ2bQSwdDLjwgr9A"
            }
          }
        }
      },
      "ServiceUnavailable": {
        "description": "Service Unavailable",
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/Error"
                },
                {
                  "title": "Error",
                  "properties": {
                    "details": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "integer"
                        },
                        "statusText": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "An error ocurred while trying to exchange a GitHub's access token": {
                "value": {
                  "statusCode": 503,
                  "error": "Service Unavailable",
                  "message": "An error ocurred while trying to exchange a GitHub's access token",
                  "code": 531,
                  "details": {
                    "status": 404,
                    "statusText": "Not Found"
                  },
                  "docs": "https://github.com/DiegoVictor/devradar-api#errors-reference"
                }
              },
              "An error ocurred while trying to retrieve the user from GitHub": {
                "value": {
                  "statusCode": 503,
                  "error": "Service Unavailable",
                  "message": "An error ocurred while trying to retrieve the user from GitHub",
                  "code": 532,
                  "details": {
                    "status": 401,
                    "statusText": "Unauthorized"
                  },
                  "docs": "https://github.com/DiegoVictor/devradar-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "scheme": "bearer",
        "type": "http"
      }
    }
  }
}
